/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ld.view;

import br.com.ld.exception.NenhumaConsultaEncontradaException;
import br.com.ld.controller.BuscaConsultaController;
import br.com.ld.model.Consulta;
import br.com.ld.model.Medico;
import br.com.ld.model.Paciente;
import br.com.ld.model.Receita;
import br.com.ld.model.Usuario;
import br.com.ld.util.FormatFactory;
import br.com.ld.util.ValidateScreen;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leonardo
 */
public class BuscarConsultasView extends javax.swing.JDialog {

    /**
     * Creates new form BuscarConsultasView
     */
    public BuscarConsultasView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        CPFpacienteInput.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    BuscarConsultas();
                }
            }
        });
        infoLabel.setVisible(false);
        VerDetalheConsultaButton.setVisible(false);
        HabilitarCamposdeBusca(usuario instanceof Medico);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CPFpacienteInput = new javax.swing.JFormattedTextField();
        PesquisarConsultaButton = new javax.swing.JButton();
        InstrucoesBuscaReceitaLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaConsultas = new javax.swing.JTable();
        VoltarParaMainButton = new javax.swing.JButton();
        VerDetalheConsultaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                aoAbrir(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));

        CPFpacienteInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CPFpacienteInputKeyReleased(evt);
            }
        });

        PesquisarConsultaButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        PesquisarConsultaButton.setText("Buscar");
        PesquisarConsultaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarConsultaButtonActionPerformed(evt);
            }
        });

        InstrucoesBuscaReceitaLabel.setBackground(new java.awt.Color(255, 255, 255));
        InstrucoesBuscaReceitaLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        InstrucoesBuscaReceitaLabel.setForeground(new java.awt.Color(255, 255, 255));
        InstrucoesBuscaReceitaLabel.setText("Digite o CPF do paciente ( apenas numeros )");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Historico de consultas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InstrucoesBuscaReceitaLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CPFpacienteInput, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PesquisarConsultaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(InstrucoesBuscaReceitaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPFpacienteInput, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PesquisarConsultaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        infoLabel.setBackground(new java.awt.Color(255, 255, 255));
        infoLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        infoLabel.setForeground(new java.awt.Color(0, 153, 51));
        infoLabel.setText("Para mais informações, selecione a consulta desejada e clique em \"Ver detalhes\".");

        TabelaConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TabelaConsultas);

        VoltarParaMainButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        VoltarParaMainButton.setText("Voltar");
        VoltarParaMainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarParaMainButtonActionPerformed(evt);
            }
        });

        VerDetalheConsultaButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        VerDetalheConsultaButton.setText("Ver detalhes");
        VerDetalheConsultaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerDetalheConsultaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(VoltarParaMainButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(VerDetalheConsultaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(infoLabel)
                .addGap(459, 459, 459))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(infoLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VerDetalheConsultaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VoltarParaMainButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private Usuario usuario = MainScreen.getUsuario();
    private ArrayList<Consulta> consultas = new ArrayList<Consulta>();

    private void RenderizarConsultas() {
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        modelo.addColumn("Codigo");
        modelo.addColumn("Data");
        modelo.addColumn("Medico");
        modelo.addColumn("Paciente");
        modelo.addColumn("Sexo");
        modelo.addColumn("Idade");
        modelo.addColumn("Sintomas");
        modelo.addColumn("Exames");
        modelo.addColumn("Dieta");
        modelo.addColumn("Receitas emitidas");

        for (Consulta cons : consultas) {
            String codigosReceitas = "";
            for (Receita r : cons.getReceitas()) {
                if (r.getId() < 1) {
                    break;
                }
                codigosReceitas += r.getId() + ", ";
            }
            // Seta os valores do objeto para a tabela 
            modelo.addRow(new Object[]{cons.getId(), FormatFactory.formatDate(cons.getData()), cons.getMedico().getNome(),
                cons.getPaciente().getNome(), cons.getPaciente().getSexo(), cons.getPaciente().getIdade(), cons.getSintomasPaciente(),
                cons.getExames(), cons.getDieta(), !codigosReceitas.isEmpty() ? codigosReceitas : "Nenhuma receita"});

        }
        //Limpa a JTable (Grid)
        TabelaConsultas.removeAll();
        //Seta o modelo para a Grid 
        TabelaConsultas.setModel(modelo);

        //Ajusta o tamanho das colunas
        TabelaConsultas.getColumnModel().getColumn(0).setPreferredWidth(15);
        TabelaConsultas.getColumnModel().getColumn(1).setPreferredWidth(25);
        TabelaConsultas.getColumnModel().getColumn(2).setPreferredWidth(150);
        TabelaConsultas.getColumnModel().getColumn(3).setPreferredWidth(150);
        TabelaConsultas.getColumnModel().getColumn(4).setPreferredWidth(8);
        TabelaConsultas.getColumnModel().getColumn(5).setPreferredWidth(8);
        TabelaConsultas.getColumnModel().getColumn(6).setPreferredWidth(200);
        TabelaConsultas.getColumnModel().getColumn(7).setPreferredWidth(150);
        TabelaConsultas.getColumnModel().getColumn(8).setPreferredWidth(200);
        TabelaConsultas.getColumnModel().getColumn(9).setPreferredWidth(90);
    }

    private boolean ValidarCampoDeBusca() {
        ValidateScreen.ValidarCampoObrigatorio(CPFpacienteInput, "CPF Paciente");

        return ValidateScreen.isCamposCorretos();
    }

    private void BuscarConsultas(String cpf) {
        try {
            BuscaConsultaController consultaController = BuscaConsultaController.getInstance();
            consultas = consultaController.BuscarConsultas(cpf);
            if (consultas == null) {
                throw new NenhumaConsultaEncontradaException();
            }
            RenderizarConsultas();
        } catch (ClassNotFoundException | SQLException e) {
        } catch (NenhumaConsultaEncontradaException | NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Este paciente ainda não possui consultas");
            if (usuario instanceof Paciente) {
                setVisible(false);
            }
        }
    }

    private void BuscarConsultas() {
        if (ValidarCampoDeBusca()) {
            BuscarConsultas(CPFpacienteInput.getText());
        }
    }
    private void CPFpacienteInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CPFpacienteInputKeyReleased
        ValidateScreen.validarNumero(CPFpacienteInput);
    }//GEN-LAST:event_CPFpacienteInputKeyReleased

    private void PesquisarConsultaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarConsultaButtonActionPerformed
        BuscarConsultas();
    }//GEN-LAST:event_PesquisarConsultaButtonActionPerformed

    private void VoltarParaMainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarParaMainButtonActionPerformed
        dispose();
    }//GEN-LAST:event_VoltarParaMainButtonActionPerformed

    private void VerDetalheConsultaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerDetalheConsultaButtonActionPerformed

    }//GEN-LAST:event_VerDetalheConsultaButtonActionPerformed

    private void aoAbrir(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_aoAbrir
        if (usuario instanceof Paciente) {
            BuscarConsultas(usuario.getDocumento());
        }
    }//GEN-LAST:event_aoAbrir

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarConsultasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarConsultasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarConsultasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarConsultasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuscarConsultasView dialog = new BuscarConsultasView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField CPFpacienteInput;
    private javax.swing.JLabel InstrucoesBuscaReceitaLabel;
    private javax.swing.JButton PesquisarConsultaButton;
    private javax.swing.JTable TabelaConsultas;
    private javax.swing.JButton VerDetalheConsultaButton;
    private javax.swing.JButton VoltarParaMainButton;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void HabilitarCamposdeBusca(boolean isMedico) {
        CPFpacienteInput.setVisible(isMedico);
        InstrucoesBuscaReceitaLabel.setVisible(isMedico);
        PesquisarConsultaButton.setVisible(isMedico);
    }
}
